character_name = str(input("Please input your character's name."))
character_age = str(input("Please input your character's age."))
print("There was once a man named " + character_name + ", ")
print("He was " + character_age + " years old.")
print("He really liked the name " + character_name + ", ")
print("But he didn't like being " + character_age + ".")