nameofplace = input("Welcome to Wizard Mad Libs!  Please enter the name of a place to start:")
boyname1 = input("Enter a boy wizard's name:")
girlname1 = input("Enter a girl wizard's name:")
disease1 = input("Enter the name of a wizard ailment:")
animal1 = input("Enter the name of a mysterious beast:")
animal2 = input("Enter the name of a delightfully silly animal:")
pet1 = input("Enter a common wizard pet:")
animalplural = input("Enter your favorite type of creepy creature, plural:")
verb1 = input("Enter a verb:")
verb2 = input("Enter a second verb:")
verb3 = input("Enter a third verb:")
adjective1 = input("Enter an adjective:")
food1 = input("Enter the name of a delicious dish:")
reptile1 = input("Enter the name of a magical reptile:")
sillyword1 = input("Enter a mysteriously silly word:")
alienverb = input("Enter a truly peculiar verb:")
classmaterial1 = input("Enter a classroom material, plural:")
exoticfood1 = input("Enter a type of truly exotic dish:")
cheapfood1 = input("Enter the food you imagine Wizard College students eat on a budget:")
kitchenfurniture1 = input("Enter a piece of furniture common in magical kitchens:")

print("Thank you for your cooperation!  Prepare yourself for a fantastically wild wizard story.")
print("Far away, in the beautiful land of " + nameofplace + ", there was a young wizard named " + boyname1 + ".")
print("Although his face was covered with " + disease1 + ", his heart was filled with wonder.")
print("Today was the young boy's first day at " + animal1 + verb1 + " Wizarding School.")
print("After boarding the " + animal1 + verb1 + " Express, he bumped into a young witch, causing quite a ruckus.")
print("'Excuse me!', she said, introducing herself as she picked up her " + food1 + " off of the floor.")
print("The boy apologized, and asked her name.")
print("The girl replied: 'Oh, that's quite alright!  My name is " + girlname1 + ".")
print("I am also attending Wizarding School.")
print("I am most excited to see the " + reptile1 + "'s exhibit, although I am very wary since I know that they")
print("tend to " + verb1 + ", which can be quite dangerous.'")
print("The boy pondered her musings, and the ride proceeded rather uneventfully.")
print("The young wizards and witches were quite exhausted from their travels.")
print("Bright and early the next day, they attended their first class, " + sillyword1 + " studies.")
print("They were surprised by the calm nature of Professor " + animal2 + alienverb)
print(boyname1 + " tried to cast a tickling spell on a particularly goofy looking " + sillyword1 + ", ")
print("But, he ended up causing an explosion of " + classmaterial1 + ", which sent all of the " + animalplural + "s")
print("running around wildly and ended up causing quite the commotion.")
print("Relieved to finally be done with classes, " + boyname1 + " and " + girlname1 + " met up in the dining hall, ")
print("where they were ready to settle down with a filling feast.")
print("'Although I am very " + adjective1 + ", I am ready to eat.  I could probably eat an entire " + pet1 + "!")
print(girlname1 + " winced a bit at his comment, but soon forgot after biting in to the fresh " + exoticfood1 + ".")
print("Although " + boyname1 + " was more interested in ravenously consuming " + cheapfood1 + ", he also hesitantly")
print("tried a bite of her " + exoticfood1 + ", before unintentionally setting the " + kitchenfurniture1 + " on fire ")
print("when he threw his hands up in disgust, forgetting he was holding his wand.")
print("All in all, it was a very eventful first day of school for " + boyname1 + " and " + girlname1)
print("at " + animal1 + verb1 + " Wizarding School.")